name: auto release
on:
  schedule:
    - cron: '48 21 * * Tue,Fri'
jobs:
  release:
    name: check version, add tag and release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
      - name: install dependencies
        run: |
          npm i
      - name: update
        run: |
          npm run-script updatedb
          npm run-script update-package
        env:
          GEOLITE2_LICENSE_KEY: ${{secrets.GEOLITE2_LICENSE_KEY}}
      - name: test
        run: npm run test
      - name: commit
        run: scripts/release.sh
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GTOKEN}}
      - name: release
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
