name: test

on:
  pull_request

jobs:
  release:
    name: node-version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['0.10', 0.12, 4, 6, 8, 10, 12, 14, 16, 18, 20]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm i
      - name: test
        run: npm run test
